In [3]:
# Reading the dataset "iris.csv"
import pandas as pd
#reading the dataset"iris.csv"
data=pd.read_csv("iris.csv")
#displaying the records
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
#displaying the number of rows randomaly
data.sample(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
106,107,4.9,2.5,4.5,1.7,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
67,68,5.8,2.7,4.1,1.0,Iris-versicolor
41,42,4.5,2.3,1.3,0.3,Iris-setosa
79,80,5.7,2.6,3.5,1.0,Iris-versicolor
109,110,7.2,3.6,6.1,2.5,Iris-virginica
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
26,27,5.0,3.4,1.6,0.4,Iris-setosa
48,49,5.3,3.7,1.5,0.2,Iris-setosa

In [5]:
#displying the number of columns and name of the columns
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [6]:
#displying the shape of the dataset
data.shape

(150, 6)

In [7]:
#displying the whole dataset
print(data)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [8]:
#slicing the rowsfrom 10th to 20th
print(data[10:21])

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa

In [9]:
#displaying only specific columns
specific_col=data[["Id","Species"]]
print(specific_col.head(10))

   Id      Species
0   1  Iris-setosa
1   2  Iris-setosa
2   3  Iris-setosa
3   4  Iris-setosa
4   5  Iris-setosa
5   6  Iris-setosa
6   7  Iris-setosa
7   8  Iris-setosa
8   9  Iris-setosa
9  10  Iris-setosa

In [10]:
#displaying the specific rows using "iloc" and "loc"
data.iloc[5]
data.loc[data["Species"] == "Iris-setosa"]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [11]:
#counting the number of counts of unique values
data["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [15]:
#calcucating sum, mean, mode of a particular column
sum_data=data["SepalLengthCm"].sum()
mean_data=data["SepalLengthCm"].mean()
median_data=data["SepalLengthCm"].median()
print("Sum:",sum_data, "\nMean:",mean_data,"\nMedian:",median_data)

Sum: 876.5
Mean: 5.843333333333334
Median: 5.8

In [18]:
#extracting minimum and maximun from a column
min_data=data["SepalLengthCm"].min()
max_data=data["SepalLengthCm"].max()
print("Maximun",max_data, "\nMinium",max_data)

Maximun 7.9
Minium 7.9

In [23]:
#adding a column to the dataset
col=data.columns
print(col)
col=col[1:5]
data1=data[col]
data["total_values"]=data1[col].sum(axis=1)
data

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species', 'total_values'],
      dtype='object')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,total_values
0,1,5.1,3.5,1.4,0.2,Iris-setosa,10.2
1,2,4.9,3.0,1.4,0.2,Iris-setosa,9.5
2,3,4.7,3.2,1.3,0.2,Iris-setosa,9.4
3,4,4.6,3.1,1.5,0.2,Iris-setosa,9.4
4,5,5.0,3.6,1.4,0.2,Iris-setosa,10.2
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,17.2
146,147,6.3,2.5,5.0,1.9,Iris-virginica,15.7
147,148,6.5,3.0,5.2,2.0,Iris-virginica,16.7
148,149,6.2,3.4,5.4,2.3,Iris-virginica,17.3
149,150,5.9,3.0,5.1,1.8,Iris-virginica,15.8

In [31]:
#renaming the column
newcols={"Id":"id","SepalLengthCm":"Sepallength", "SepalWidthCm":"Sepalwidth"}
data.rename(columns=newcols,inplace=True)
print(data.head())

   id  Sepallength  Sepalwidth  PetalLengthCm  PetalWidthCm      Species  \
0   1          5.1         3.5            1.4           0.2  Iris-setosa
1   2          4.9         3.0            1.4           0.2  Iris-setosa
2   3          4.7         3.2            1.3           0.2  Iris-setosa
3   4          4.6         3.1            1.5           0.2  Iris-setosa
4   5          5.0         3.6            1.4           0.2  Iris-setosa

   total_values
0          10.2
1           9.5
2           9.4
3           9.4
4          10.2

In [34]:
#cleaning and detecting missing values
data.isnull()

,id,Sepallength,Sepalwidth,PetalLengthCm,PetalWidthCm,Species,total_values
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
145,False,False,False,False,False,False,False
146,False,False,False,False,False,False,False
147,False,False,False,False,False,False,False
148,False,False,False,False,False,False,False
149,False,False,False,False,False,False,False

In [33]:
#summarizing the missing values
data.isnull().sum()

id               0
Sepallength      0
Sepalwidth       0
PetalLengthCm    0
PetalWidthCm     0
Species          0
total_values     0
dtype: int64

In [37]:
#delete the column
df=data.drop('PetalLengthCm', axis=1)
print(df)

      id  Sepallength  Sepalwidth  PetalWidthCm         Species  total_values
0      1          5.1         3.5           0.2     Iris-setosa          10.2
1      2          4.9         3.0           0.2     Iris-setosa           9.5
2      3          4.7         3.2           0.2     Iris-setosa           9.4
3      4          4.6         3.1           0.2     Iris-setosa           9.4
4      5          5.0         3.6           0.2     Iris-setosa          10.2
..   ...          ...         ...           ...             ...           ...
145  146          6.7         3.0           2.3  Iris-virginica          17.2
146  147          6.3         2.5           1.9  Iris-virginica          15.7
147  148          6.5         3.0           2.0  Iris-virginica          16.7
148  149          6.2         3.4           2.3  Iris-virginica          17.3
149  150          5.9         3.0           1.8  Iris-virginica          15.8

[150 rows x 6 columns]

In [38]:
#drop multiple columns
df=data.drop(['Sepallength', 'Sepalwidth'],axis=1)
print(df)

      id  PetalLengthCm  PetalWidthCm         Species  total_values
0      1            1.4           0.2     Iris-setosa          10.2
1      2            1.4           0.2     Iris-setosa           9.5
2      3            1.3           0.2     Iris-setosa           9.4
3      4            1.5           0.2     Iris-setosa           9.4
4      5            1.4           0.2     Iris-setosa          10.2
..   ...            ...           ...             ...           ...
145  146            5.2           2.3  Iris-virginica          17.2
146  147            5.0           1.9  Iris-virginica          15.7
147  148            5.2           2.0  Iris-virginica          16.7
148  149            5.4           2.3  Iris-virginica          17.3
149  150            5.1           1.8  Iris-virginica          15.8

[150 rows x 5 columns]