In [25]:
import pandas as pd 
import scipy as sp 
import numpy as np 
filepath ="diamonds.csv" 
df = pd.read_csv(filepath).iloc[:, [1,2,0]] 
df.head()

   depth  price  carat
0   61.5    326   0.23
1   59.8    326   0.21
2   56.9    327   0.23
3   62.4    334   0.29
4   63.3    335   0.31

In [26]:
def mahalanobis(x=None, data=None, cov=None):
    x = np.asarray(x)
    data = np.asarray(data)
    mu = np.mean(data, axis=0)
    x_minus_mu = x - mu
    if cov is None:
        cov = np.cov(data, rowvar=False)
    inv_covmat = sp.linalg.inv(cov)
    left_term = np.dot(x_minus_mu, inv_covmat)
    mahal = np.dot(left_term, x_minus_mu.T)
    return np.sqrt(np.diagonal(mahal))
df_x = df[['carat', 'depth', 'price']].head(500)
df_x['mahala'] = mahalanobis(
    x=df_x.values,
    data=df[['carat', 'depth', 'price']].values
)
df_x.head()

   carat  depth  price    mahala
0   0.23   61.5    326  1.702724
1   0.21   59.8    326  1.617093
2   0.23   56.9    327  1.787093
3   0.29   62.4    334  1.214650
4   0.31   63.3    335  1.347838