In [3]:
import pandas as pd
#reading csv file
df=pd.read_csv("Team.csv")
df

     Name    Team  Number Position   Age
0   avery  boston     0.0       GP  25.0
1   john   boston    30.0       SG  27.0
2   jonas  boston    30.0       PF  29.0
3  jordan  boston     8.0       PG  21.0
4   terry  boston     NaN        C  22.0
5   jared  boston    12.0       SG   NaN
6    evan  boston    11.0       SG  27.0

In [8]:
#head() method
df.head(5)

     Name    Team  Number Position   Age
0   avery  boston     0.0       GP  25.0
1   john   boston    30.0       SG  27.0
2   jonas  boston    30.0       PF  29.0
3  jordan  boston     8.0       PG  21.0
4   terry  boston     NaN        C  22.0

In [9]:
#tail() function
df.tail(4)

     Name    Team  Number Position   Age
3  jordan  boston     8.0       PG  21.0
4   terry  boston     NaN        C  22.0
5   jared  boston    12.0       SG   NaN
6    evan  boston    11.0       SG  27.0

In [10]:
#info function
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      7 non-null      object
 1   Team      7 non-null      object
 2   Number    6 non-null      float64
 3   Position  7 non-null      object
 4   Age       6 non-null      float64
dtypes: float64(2), object(3)
memory usage: 412.0+ bytes

In [13]:
#dtypes() function
df.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
dtype: object

In [17]:
#shape() function
df.shape

(7, 5)

In [18]:
#size() function
df.size

35

In [19]:
#describe() function
df.describe

<bound method NDFrame.describe of      Name    Team  Number Position   Age
0   avery  boston     0.0       GP  25.0
1   john   boston    30.0       SG  27.0
2   jonas  boston    30.0       PF  29.0
3  jordan  boston     8.0       PG  21.0
4   terry  boston     NaN        C  22.0
5   jared  boston    12.0       SG   NaN
6    evan  boston    11.0       SG  27.0>